[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build"]
dependencies = ["clean"]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["clean"]

[tasks.my-flow]
dependencies = [
    "format",
    "build",
    "test"
]




[tasks.start-case-data-api]
description = "Start the case_data_api"
command = "cargo"
args = ["run", "--package", "case_data_api"]
cwd = "case_data_api/"

[tasks.start-participants-api]
description = "Start the participants_api"
command = "cargo"
args = ["run", "--package", "participants_api"]
cwd = "participants_api/"

[tasks.start-all]
description = "Start all APIs"
dependencies = ["start-case-data-api", "start-participants-api"]


